set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

""""" Lines added by the user start here

" Use Ctrl - B to open a file browser
Plugin 'scrooloose/nerdtree'

" Nice visual for the status bar
Plugin 'vim-airline/vim-airline'

" Syntax checker for vim, it can really slow it down sometimes
Plugin 'vim-syntastic/syntastic'

" A nice dark theme
Plugin 'ajmwagar/vim-deus'

" This helps with the parentheses and brackets
Plugin 'tpope/vim-surround'

" Use gcc to comment out a line, gc to comment the visual selection, gcap to comment a paragraph
Plugin 'tpope/vim-commentary'

" Toogle indent guides on and off with <leader>ig (leader is /)
Plugin 'nathanaelkane/vim-indent-guides'

" Simple autocompletion
Plugin 'ervandew/supertab'

" Autocompletion for html structures
Plugin 'mattn/emmet-vim'

Plugin 'kelwin/vim-smali'


"""""" Lines added by the user end here

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Sets the moving numbers on the right
set relativenumber

" Enable mouse!
set mouse=v

" Set Ctrl - b as shortcut for opening NERDTree
map <C-b> :NERDTreeToggle<CR>
" let nerdtree use the mouse
let g:NERDTreeMouseMode=3

"" Indentation Stuff
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set textwidth=100

"" Exit with :WQ :Wq :wQ etc.
 cnoreabbrev W! w!
 cnoreabbrev Q! q!
 cnoreabbrev Qall! qall!
 cnoreabbrev Wq wq
 cnoreabbrev Wa wa
 cnoreabbrev wQ wq
 cnoreabbrev WQ wq
 cnoreabbrev W w
 cnoreabbrev Q q
 cnoreabbrev Qall qall

" Theme settings
set termguicolors
colorscheme deus

" Disable those annoying swap files
set noswapfile

" Syntastic configuration

" set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Highlight current line
set cursorline

" Color column at 80
set cc=80

" Maintain undo history between sessions in a certain directory
set undofile
set undodir=~/.vim/undo_history

" Function for toggling vim colorscheme
nnoremap ,<space> :call ColorSchemeToggle()<cr>

let g:colorscheme_is_white=0

function! ColorSchemeToggle()
    " if colorscheme is white, make it dark
    if g:colorscheme_is_white
        colorscheme deus
        let g:colorscheme_is_white=0
    else
        colorscheme morning
        let g:colorscheme_is_white=1
    endif
endfunction

" Fire emmet plugin up just for html/css
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall

" Cool syntax highlight
autocmd BufNewFile,BufRead *.cl set filetype=cool

" Use nasm syntax for .asm files
" autocmd BufNewFile,BufRead *.asm set filetype=nasm

" Antlr4 syntax
autocmd BufRead,BufNewFile *.g4 set filetype=antlr4

syntax on



