alias o=xdg-open
alias n=nautilus
alias p=python
alias chx='chmod +x'

alias reset-sound='sudo killall -9 pulseaudio; pulseaudio >/dev/null 2>&1 &'
alias ida='$HOME/packages/idademo70/ida'
alias vim=nvim
